site_name: Searching-As-Code In A Day
site_url: https://bakermat.github.io/searching-as-code
site_description: Get to the choppah!
repo_name: bakermat/searching-as-code
repo_url: https://github.com/bakermat/searching-as-code
edit_uri: ''

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo


    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: pink

  font:
    text: Roboto
    code: Roboto Mono
  include_search_page: false
  search_index_only: true
  language: en
  custom_dir: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - toc.integrate

extra:
  version: 0.1
  frontpage_header: 'This is the first line.'
  frontpage_subtitle: 'This is, you guessed it, the second line.'

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - attr_list

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - First step: getting-started.md
    - Second step: next-step.md
  - Reference:
    - Cloud API: reference/cloud.md
  - Resources:
    - Links: resources/links.md
