name: splunkcloud
on:
  push:
    branches:
      # change this to main once done with testing
      - main
jobs:
  deploy:
    name: Deploy to Splunk Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Parse YAML File
      # This action doesn't seem to work anymore
      # uses: CumulusDS/get-yaml-paths-action@v0.1.0
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: parseyaml
        with:
          #file: apps/searchingascode/searches/winRateByTier.yaml
          path: apps/searchingascode/searches/winRateByTier.yaml
          from: yaml
          to: yaml
      - name: Print YAML result
        env:
          SHORTNAME: "${{ steps.parseyaml.outputs.data.shortname }}"
          SEARCH: "${{ steps.parseyaml.outputs.data.search }}"
          VERSION: "${{ steps.parseyaml.outputs.data.version }}"
          APP: "${{ steps.parseyaml.outputs.data.app }}"
        run: echo "${{ steps.parseyaml.outputs.data }}"
      - name: Push to Splunk Cloud
        env:
          USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
          URL: ${{ secrets.URL }}

        run: |
          CODE="curl -k -u $USERNAME:$PASSWORD https://$URL:8089/servicesNS/admin/$APP/saved/searches -d name=$SHORTNAME -d search=$SEARCH"
          if [ $CODE!="200"]
          then
            curl -k -u user:passw https://$URL:8089/servicesNS/admin/$APP/saved/searches/$SHORTNAME  -d search=$SEARCH
            echo "Updated $SHORTNAME."
          else
            echo "Created $SHORTNAME."
          fi
