name: splunkcloud
on:
  push:
    branches:
      # change this to main once done with testing
      - main
jobs:
  deploy:
    name: Deploy to Splunk Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Parse YAML File
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: winRateByTier.yaml
        env:
          INPUT_SEARCH: search
          INPUT_NAME: name
          INPUT_VERSION: version
      - name: Push to Splunk Cloud
        env:
          USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
          URL: ${{ secrets.URL }}
        run: |
          CODE="curl -k -u user:passw https://scb-o2-ohgwyyq7dpzxksr.stg.splunkcloud.com:8089/servicesNS/admin/searchingascode/saved/searches -d name=$INPUT_NAME --data-urlencode search=$INPUT_SEARCH"
          if [ $CODE!="200"]
          then
            curl -k -u user:passw https://scb-o2-ohgwyyq7dpzxksr.stg.splunkcloud.com:8089/servicesNS/admin/searchingascode/saved/searches/$INPUT_NAME --data-urlencode search=$INPUT_SEARCH"
            echo "Updated $INPUT_NAME."
          else
            echo "Created $INPUT_NAME."
          fi