name: splunkcloud
on:
  push:
    branches:
      # change this to main once done with testing
      - main
jobs:
  deploy:
    name: Parse YAML file & push search to Splunk Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Parse YAML File
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: parseyaml
        with:
          path: apps/searchingascode/searches/winRateByTier.yaml
          from: yaml
          to: json
      - name: Get relevant fields from JSON file
        run: | 
          echo '${{ steps.parseyaml.outputs.data }}' | jq -r '"SHORTNAME="+.shortname' >> "$GITHUB_ENV"
          echo '${{ steps.parseyaml.outputs.data }}' | jq -r '"SEARCH="+.search' >> "$GITHUB_ENV"
          echo '${{ steps.parseyaml.outputs.data }}' | jq -r '"VERSION="+(.version|tostring)' >> "$GITHUB_ENV"
          echo '${{ steps.parseyaml.outputs.data }}' | jq -r '"APP="+.app' >> "$GITHUB_ENV"
      - name: Push to Splunk Cloud
        env:
          USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
          URL: ${{ secrets.URL }}
        run: |
          echo "Hello"
          echo $SHORTNAME
          echo $SEARCH
          echo $URL
          "curl -k -u $USERNAME:$PASSWORD https://$URL:8089/servicesNS/admin/$APP/saved/searches -d name=$SHORTNAME -d search=$SEARCH"
        # CODE="curl -k -u $USERNAME:$PASSWORD https://$URL:8089/servicesNS/admin/$APP/saved/searches -d name=$SHORTNAME -d search=$SEARCH"
        # if [ $CODE!="200" ]
        # then
        #   curl -k -u user:passw https://$URL:8089/servicesNS/admin/$APP/saved/searches/$SHORTNAME  -d search=$SEARCH
        #   echo "Updated $SHORTNAME."
        # else
        #   echo "Created $SHORTNAME."
        # fi
