name: splunkcloud
on:
  push:
    branches:
      # change this to main once done with testing
      - main
jobs:
  deploy:
    name: Parse YAML file & push search to Splunk Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Parse YAML File
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: parseyaml
        with:
          path: apps/searchingascode/searches/winRateByTier.yaml
          from: yaml
          to: json
      - name: Get relevant fields from JSON file
        run: | 
          shortname='${{ steps.parseyaml.outputs.data }}' | jq '.shortname'
          search='${{ steps.parseyaml.outputs.data }}' | jq '.search'
          version='${{ steps.parseyaml.outputs.data }}' | jq '.version'
          app='${{ steps.parseyaml.outputs.data }}' | jq '.app'
          echo "SHORTNAME=$shortname" >> "$GITHUB_ENV"
          echo "SEARCH=$search" >> "$GITHUB_ENV"
          echo "VERSION=$version" >> "$GITHUB_ENV"
          echo "APP=$app" >> "$GITHUB_ENV"
      - name: Push to Splunk Cloud
        env:
          USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
          URL: ${{ secrets.URL }}
        run: |
          CODE="curl -k -u $USERNAME:$PASSWORD https://$URL:8089/servicesNS/admin/$APP/saved/searches -d name=$SHORTNAME -d search=$SEARCH"
          if [ $CODE!="200" ]
          then
            curl -k -u user:passw https://$URL:8089/servicesNS/admin/$APP/saved/searches/$SHORTNAME  -d search=$SEARCH
            echo "Updated $SHORTNAME."
          else
            echo "Created $SHORTNAME."
          fi
